---
engines:
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  fixme:
    enabled: true
    exclude_fingerprints:
    - 9b1a9060d3684be85a832e44ca1ea7dd
  rubocop:
    enabled: true
    checks:
      Rubocop/Lint/AssignmentInCondition:
        enabled: false
ratings:
  paths:
  - Gemfile.lock
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
- test/
- README.md
